# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FreeStreamer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FreeStreamer

  target 'FreeStreamerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FreeStreamerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'FreeStreamer'

end
